### ISSUE TITLE
TypeError: indicatorName is undefined

### ISSUE THREAD

**Issue by amogus07** [shendrew/Lilypad#1]
the extension's settings page only shows lilypad itself

**Comment by amogus07** [comment]
ok nvm, the same error is showing up for other extensions, so it's likely a problem on my end

**Comment by amogus07** [comment]
ok, now there's a different error: TypeError: indicatorName is undefined

**Comment by shendrew** [comment]
@amogus07 Hi there, thanks for bringing this issue up, I'm looking into it right now. Would you be able to provide a list of some of the extensions with icons that you are using?

**Comment by rsilvr** [comment]
@shendrew I believe the version published in Gnome Extensions repository is earlier than this fix? Installing from there I still got the "indicatorName is undefined" error. Installing directly from your main branch is working fine

**Comment by shendrew** [comment]
@rsilvr that's good to hear! I have been working on resolving some other issues, but the fix for the indicatorName has been submitted now, and is waiting for reviews.
