### ISSUE TITLE
Increase support for GNOME 47

### ISSUE THREAD

**Issue by Anifyuli** [shendrew/Lilypad#14]
Hello Mister.
I want to remind you to updating this extension support for GNOME 47. I wish this extension can support newer GNOME version. Thanks for your hardwork.

**Comment by shendrew** [comment]
Thank you for the reminder! There doesn't seem to be any major changes for GNOME 47, so it has been added in the metadata for supported versions in recent commits.

I can officially upload it to GNOME extensions for review once I setup a VM and test it there in the coming weeks.

**Comment by Scridgeon** [comment]
I'm looking forward to this update as well.

**Comment by shendrew** [comment]
Hi everyone! Thank you for your patience in the last couple of weeks.

Had some trouble setting up a VM, but now version 1.0.3 with support for GNOME 47 has been submitted for review, and will hopefully be approved before the winter holidays. Cheers!
