### ISSUE TITLE
InternalError: too much recursion

### ISSUE THREAD

**Issue by danielbmeireles** [shendrew/Lilypad#3]
Hello!

My extension is broken, and I don't know how to fix the error:

InternalError: too much recursion

I tried to remove and re-add the extension, but the error persisted.

If you need any information from me, please let me know!

**Comment by shendrew** [comment]
Hi @danielbmeireles ! I will look into this issue.

If you could share a short list of your extensions that have indicators, that would be very helpful for recreating the issue on my end. Thanks!

**Comment by danielbmeireles** [comment]
Something like that?
![Screenshot from 2024-09-02 16-25-37](https://github.com/user-attachments/assets/5059ba74-b04d-4083-9697-cb14aebe7e1a)

**Comment by shendrew** [comment]
I tested some of the extensions/apps listed but haven't encountered the issue yet.

Could you please help me with some additional info?
-what action does it take to trigger the error (eg: on start, opening another app, etc.) 
-what apps do "67d095d2..." and "kde.StatusNotifierItem-7415.." refer to

(I think these names are what the shell refers to the app indicator containers as and should be static, looking to add more readable aliases in the future)

**Comment by danielbmeireles** [comment]
Hello!

The error is no longer present in my system. Maybe the new update fixed the issue?

**Comment by shendrew** [comment]
That's wonderful! :tada: 

I'll mark this as resolved for now
