### ISSUE TITLE
Suggestions : Move "Clear" option to extension settings

### ISSUE THREAD

**Issue by Anifyuli** [shendrew/Lilypad#4]
Hello Mister.
This day I tried your extension, and its good. I want give some suggestions for making this extension better than now. It is, please move the "Clear" option to the extension setting for UX improvements. If it (I mean "Clear") is located on the right-click menu, it can be accidentally clicked and configured settings forgot.
![image](https://github.com/user-attachments/assets/fe9473d6-1abc-408e-8246-d154a87f336d)

Be better to move it to here (extension setting). You can put it on top (beside window control button) or on bottom in dedicated button.
![image](https://github.com/user-attachments/assets/ee9c986f-2832-4d3a-aed0-786a31d8314b)

Thanks for read my issue. I wish you implement it on next updates. Sorry my English 🙏🏼

**Comment by shendrew** [comment]
Hi there, really appreciate for the feedback.

I moved the "Clear" button to the settings menu like so: (hope it helps prevent accidental resets!)
![Screenshot from 2024-09-03 18-03-14](https://github.com/user-attachments/assets/76b384b1-7fb1-4c84-9328-2a3715230077)

**Comment by Anifyuli** [comment]
Thanks Bro for your updates. I looks better
